
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Hero } from "./_components/Hero";
import { Spotlight } from "@/components/ui/spotlight";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  
        <Spotlight
        className="-top-40 left-0 md:left-60 md:-top-20"
        fill="orange"
      />
        <Navbar />
        <Hero />
     
        {children}
      </body>
    </html>
  );
}
